"""Pure, fail-closed machine execution domain contracts."""

from drawingmachine.domain.jobs.models import MachineJobOutcomeTransition
from drawingmachine.domain.machine.approvals import (
    ApprovalPurpose,
    ApprovalStatus,
    AuthenticatedMachinePrincipal,
    KernelMachinePrincipal,
    MachineApprovalBinding,
    MachineApprovalChallenge,
    MachineApprovalDecision,
    MachineApprovalEvidenceV1,
    apply_approval_decision,
    consume_approval,
    expire_approval,
    issue_approval,
    supersede_approval,
)
from drawingmachine.domain.machine.events import (
    MachineAuditPayloadV1,
    MachineAuditPayloadV2,
    MachineEvent,
    MachineEventPayloadV1,
    MachineEventPayloadV2,
)
from drawingmachine.domain.machine.models import (
    MachineExecution,
    MachineFailureEvidenceV1,
    MachineMotionEvidenceKind,
    MachineMotionRecoveryEvidenceV1,
    MachineMotionStep,
    MachineOutcome,
    MachineOutcomeKind,
    MachineRecoveryEvidence,
    MachineSessionSnapshot,
    OwnerRetirementEvidence,
    RetirementDisposition,
    StreamMilestone,
)
from drawingmachine.domain.machine.phases import (
    MachineAction,
    MachinePhase,
    RecoveryDisposition,
    RecoveryIntent,
)
from drawingmachine.domain.machine.progress import MachineProgress

__all__ = [
    "ApprovalPurpose",
    "ApprovalStatus",
    "AuthenticatedMachinePrincipal",
    "KernelMachinePrincipal",
    "MachineAction",
    "MachineApprovalBinding",
    "MachineApprovalChallenge",
    "MachineApprovalDecision",
    "MachineApprovalEvidenceV1",
    "MachineAuditPayloadV1",
    "MachineAuditPayloadV2",
    "MachineEvent",
    "MachineEventPayloadV1",
    "MachineEventPayloadV2",
    "MachineExecution",
    "MachineFailureEvidenceV1",
    "MachineJobOutcomeTransition",
    "MachineMotionEvidenceKind",
    "MachineMotionRecoveryEvidenceV1",
    "MachineMotionStep",
    "MachineOutcome",
    "MachineOutcomeKind",
    "MachinePhase",
    "MachineProgress",
    "MachineRecoveryEvidence",
    "MachineSessionSnapshot",
    "OwnerRetirementEvidence",
    "RecoveryDisposition",
    "RecoveryIntent",
    "RetirementDisposition",
    "StreamMilestone",
    "apply_approval_decision",
    "consume_approval",
    "expire_approval",
    "issue_approval",
    "supersede_approval",
]
