from __future__ import annotations

from enum import StrEnum


class RecoveryIntent(StrEnum):
    PRE_STREAM_RESTART = "PRE_STREAM_RESTART"
    STREAM_AMBIGUOUS_RELEASE_ONLY = "STREAM_AMBIGUOUS_RELEASE_ONLY"
    POST_STREAM_SAFE_HOME = "POST_STREAM_SAFE_HOME"


class RecoveryDisposition(StrEnum):
    RELEASE = "RELEASE"
    RESTART_SEQUENCE = "RESTART_SEQUENCE"
    SAFE_HOME = "SAFE_HOME"


class MachineAction(StrEnum):
    PREPARE_SESSION = "PREPARE_SESSION"
    HOME = "HOME"
    ZCAL = "ZCAL"
    ZCONFIRM = "ZCONFIRM"
    STREAM = "STREAM"
    HOME_Z = "HOME_Z"
    RECOVER = "RECOVER"


class MachinePhase(StrEnum):
    PREPARING_SESSION = "PREPARING_SESSION"
    AWAITING_HOME_APPROVAL = "AWAITING_HOME_APPROVAL"
    HOMING = "HOMING"
    AWAITING_ZCAL_APPROVAL = "AWAITING_ZCAL_APPROVAL"
    Z_CALIBRATING = "Z_CALIBRATING"
    AWAITING_ZCONFIRM_APPROVAL = "AWAITING_ZCONFIRM_APPROVAL"
    Z_CONFIRMING = "Z_CONFIRMING"
    AWAITING_STREAM_APPROVAL = "AWAITING_STREAM_APPROVAL"
    STREAMING = "STREAMING"
    AWAITING_HOME_Z_APPROVAL = "AWAITING_HOME_Z_APPROVAL"
    HOMING_Z = "HOMING_Z"
    COMPLETED = "COMPLETED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
